Repository itszechs/DriveStream, pull requests merged in 2022-06, with the labels that each got.

#8 Improved pagination ui
  app/src/main/java/zechs/drive/stream/ui/files/FilesFragment.kt
  app/src/main/java/zechs/drive/stream/ui/files/FilesViewModel.kt
  app/src/main/java/zechs/drive/stream/ui/files/adapter/FilesAdapter.kt
  app/src/main/java/zechs/drive/stream/ui/files/adapter/FilesDataModel.kt
  app/src/main/java/zechs/drive/stream/ui/files/adapter/FilesItemDiffCallback.kt
  app/src/main/java/zechs/drive/stream/ui/files/adapter/FilesViewHolder.kt
  app/src/main/res/layout/fragment_files.xml
  app/src/main/res/layout/item_loading.xml
Labels: enhancement

#16 Fix readme typo
  README.md
Labels: documentation

#21 Feature: Log out from account
  app/src/main/java/zechs/drive/stream/data/remote/DriveHelper.kt
  app/src/main/java/zechs/drive/stream/ui/home/HomeFragment.kt
  app/src/main/java/zechs/drive/stream/ui/home/HomeViewModel.kt
  app/src/main/java/zechs/drive/stream/ui/main/MainActivity.kt
  app/src/main/java/zechs/drive/stream/ui/main/MainViewModel.kt
  app/src/main/res/drawable/ic_logout_24.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#24 Feature: Ability to lock playback controls
  app/src/main/java/zechs/drive/stream/ui/player/PlayerActivity.kt
  app/src/main/res/drawable/ic_lock_24.xml
  app/src/main/res/drawable/ic_unlock_24.xml
  app/src/main/res/layout/player_control_view.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Added app icon
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement, good first issue
